let obj = {
    RANDOM_MATCH: 1,  // 随机匹配
    PROPERTY_MATCH: 2,  // 属性匹配
    MAX_PLAYER_COUNT: 2,
    shortstr:'',
    token:"",
    isWin:false,
    score:0,
    A:'A',
    begin:false,
    channel: 'Matchvs',
    platform: 'alpha',
    gameID: 215269,
    openid:"",
    session:"",
    secret:'52e539d0d4b749bebf8b0ba1b0848e99',
    gameVersion: 1,
    appKey: '70445bad1c384737b9f428246401b5ed#C',
    isWX:false,
    matchType: 1,
    tagsInfo: {"title": "A"},
    frameInfo: {"title" : "frameInfo"},
    userID: 0,
    name: "",
    avatar: "",
    ARROW_LEFT: 1,
    ARROW_RIGHT: 2,
    ARROW_STOP: 0,
    playerUserIds: [],
    isRoomOwner:false,
    syncFrame: false,
    FRAME_RATE: 20,
    roomID: 0,
    playertime: 60,
    isGameOver: false,
    NEW_STAR_POSITION : 0,
    number1: "",
    number2: "",
    number3: "",
    ownew:0, //只为做分数展示时判断使用
    mapType: "",
    FPS:30,//数据帧每秒采样次数
};

module.exports = obj;